### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by zhouyunjian** [MatsMoll/Emby-Player-iOS#1]
error: Build input files cannot be found: '/Users/yun/Documents/Frameworks/Views/VisibleTextField.swift', '/Users/yun/Documents/Frameworks/Views/UIViewExtension.swift'

**Comment by MatsMoll** [comment]
@zhouyunjian I have tried to add the missing files, so what happens if you pull and build now?
```bash
git pull master
pod install
```
