### ISSUE TITLE
Can I fork and relicense this code MPL?

### ISSUE THREAD

**Issue by sparky8251** [MatsMoll/Emby-Player-iOS#2]
Hey there, I stumbled across this repo and would like to make use of it.

I help out over at Jellyfin which is an open-source fork of Emby from before they went closed source.

I ask specifically for MPL because [Apple forbids the acceptance of GPL into their app stores](https://www.fsf.org/news/2010-05-app-store-compliance) and the MPL is the most restrictive license we can place ourselves under while still getting onto the app stores (in an attempt to keep the code we fork forever open).

Thanks for getting back to me! :)

**Comment by MatsMoll** [comment]
Hi @sparky8251 ! 

Thanks for the request!

I would be happy to let you use the codebase for the Jellyfin project. So go ahead and relicense the code under MPL. But be aware that the code is not well documented, contains no tests, and written to support iOS 9. However, it should be able to stream, search, and download most content. I can probably explain some of the code if needed, but right now will I not have the time to contribute myself.

**Comment by sparky8251** [comment]
Thanks so much! Hopefully we can find some swift devs looking to give it new life now that we've forked it. Chances are it'll be a huge improvement over our expo app!
